<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE Mapping [ <!ELEMENT Mapping (MethodName+)> <!ATTLIST MethodName 
	name CDATA #REQUIRED> <!ATTLIST MethodName testData CDATA #REQUIRED> <!ATTLIST 
	MethodName clientEnvironment CDATA #REQUIRED> <!ATTLIST MethodName runStrategy 
	CDATA #IMPLIED> ]> -->

<!DOCTYPE Mapping [ <!ELEMENT Mapping (Package+)> 
<!ATTLIST Package name CDATA #REQUIRED>
<!ATTLIST Package testData CDATA #IMPLIED> 
<!ATTLIST Package clientEnvironment CDATA #IMPLIED>
<!ATTLIST Package runStrategy (Full|Optimal) #IMPLIED> 
<!ELEMENT Package (Class*)>
<!ATTLIST Class name CDATA #REQUIRED>
<!ATTLIST Class clientEnvironment CDATA #IMPLIED>
<!ATTLIST Class testData CDATA #IMPLIED> 
<!ATTLIST Class runStrategy (Full|Optimal) #IMPLIED>
<!ELEMENT Class (MethodName*)>
<!ATTLIST MethodName name CDATA #REQUIRED> 
<!ATTLIST MethodName testData CDATA #IMPLIED> 
<!ATTLIST MethodName clientEnvironment CDATA #IMPLIED> 
<!ATTLIST MethodName runStrategy (Full|Optimal) #IMPLIED>]>



<!-- <Mapping> <MethodName name = "com.springer.tests.LoginTests.simpleLoginTest" 
	testData = "Login_Data.xml" clientEnvironment = "Desktop.xml" runStrategy 
	= "Optimal"/> <MethodName name = "com.springer.tests.CheckOutTests.checkOutProcess" 
	testData = "Login_Data.xml" clientEnvironment = "Desktop.xml" runStrategy 
	= "Optimal"/> <MethodName name = "com.springer.tests.CheckOutTests.checkOutProcessSearchBook" 
	testData = "Login_Data.xml" clientEnvironment = "Desktop.xml" /> </Mapping> -->

<Mapping>

	<Package name="com.springer.tests" testData="data/CheckOut_Stage_Data.xml" runStrategy="Optimal">
		<Class name="CheckOutTests" clientEnvironment="browsers/Desktop.xml">
		    
			<!-- <MethodName name="checkOutProcessSearchBook_live" testData="data/CheckOut_Stage_Data.xml" /> -->
			<!-- <MethodName name="MutipleBookCheckOut" testData=/> -->
			<MethodName name="checkOutProcessSearchBook" testData="data/CheckOut_Stage_Data.xml"/>
			

		</Class>

		<Class name="LoginTests" clientEnvironment="browsers/Desktop.xml"
			testData="data/Login_Stage_Data.xml">
		</Class>

		<Class name="RegistrationTest">
			<MethodName name="simpleRegistrationTest"
				clientEnvironment="browsers/Desktop.xml" testData="data/NewRegistration_Stage_Data.xml" />
		</Class>

		<Class name="Stage150Tests" clientEnvironment="browsers/BSFireFox.xml"
			testData="data/Stage150_Stage_Data.xml">

		</Class>
		<Class name="ORCTest" clientEnvironment="browsers/BSFireFox.xml" testData="data/ORC_Stage_Data.xml">
		
		</Class>		
		<Class name="BookSellerWebShop" clientEnvironment="browsers/BSFireFox.xml" testData="data/BookSeller_Stage_Data.xml">
		</Class>
		<Class name = "ShopLandingPageTests" clientEnvironment="browsers/BSFireFox.xml" testData="data/ShopLanding_Stage_Data.xml"/>
		<Class name = "SsoTests" clientEnvironment="browsers/FireFoxLocal.xml" testData="data/Sso_live_Data.xml"/>
		
		<Class name = "NewProductPageTests" clientEnvironment="browsers/FireFoxLocal.xml" testData="data/NewProductPage_Stage_Data.xml"/>
		<!-- <Class name="CheckOutTests" > <MethodName name="checkOutProcessSearchBook" 
			/> </Class> -->

	</Package>
</Mapping>

